#!/usr/bin/tclsh

package require udp

set sock [udp_open]
udp_conf $sock localhost 9093
fconfigure $sock -buffering none -translation binary

foreach a $argv {
    if {[string equal $a -]} {
        while {[gets stdin a] >= 0} {
            puts $sock $a
        }
    } else {
        puts $sock $a
    }
}
